sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm install -g yarn
install:
  - yarn
after_script:
  - yarn run coveralls
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
